apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service_name }}
spec:
  selector:
    app: {{ .Values.api.app_name }}
  ports:
    - name: api-http
      protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
  {{- if not .Values.ambassador.in_helx }}
    {{- if .Values.mongo_express.enabled }}
    - name: mongo-express-http
      protocol: TCP
      port: {{ .Values.mongo_express.port }}
      targetPort: {{ .Values.mongo_express.port }}
    {{- end }}
  {{- end }}
